### ISSUE TITLE
where is the dataset?

### ISSUE THREAD

**Issue by SeekPoint** [yvchen/ContextualSLU#1]
$ bash script/run_sample.sh rnn theano 0 | sh
Using TensorFlow backend.
Traceback (most recent call last):
  File "program/SequenceTagger.py", line 5, in <module>
    from BasicModel import KerasModel
  File "/ContextualSLU/program/BasicModel.py", line 15, in <module>
    from keras.layers import Input, merge, Merge, Dense, TimeDistributedDense, Dropout, Activation, RepeatVector, Permute, Reshape, RepeatVector, Flatten
ImportError: cannot import name TimeDistributedDense
$ bash script/run_sample.sh rnn theano 0 | sh
Using TensorFlow backend.
Traceback (most recent call last):
  File "program/SequenceTagger.py", line 60, in <module>
    KerasModel(argparams).run()
  File "/ContextualSLU/program/BasicModel.py", line 614, in run
    trainData = dataSet(self.training_file,'train',emptyVocab,emptyVocab,emptyIndex,emptyIndex)
  File "/ContextualSLU/program/wordSlotDataSet.py", line 17, in __init__
    self.dataSet = readData(dataFile)
  File "/ContextualSLU/program/wordSlotDataSet.py", line 158, in readData
    for line in open(dataFile, 'r'):
IOError: [Errno 2] No such file or directory: 'data/cortana.communication.5.train.iob'

**Comment by SeekPoint** [comment]
I use the atas-2 dataset in JointSLU like

--- a/script/run_sample.sh
+++ b/script/run_sample.sh
@@ -1,9 +1,9 @@
 DOMAIN=cortana.communication.5
 DATADIR=data
 PROG=program/SequenceTagger.py
-TRAIN=$DATADIR/"$DOMAIN".train.iob
-TEST=$DATADIR/"$DOMAIN".test.iob
-DEV=$DATADIR/"$DOMAIN".dev.iob
+TRAIN=../JointSLU/data/atis-2.train.iob
+DEV=../JointSLU/data/atis-2.dev.iob
+TEST=../JointSLU/data/atis.test.iob
 RES_PATH=sample
 MDL_PATH=sample

is that OK?

**Comment by wangfeng0621** [comment]
你好！请问您的数据能够给我一份吗？或者给一个地址，我自己去下载。
